# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aluno
      MYSQL_DATABASE: curso
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=aluno --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 10s
      retries: 10

  dbscript:
    build: .
    restart: always
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "python3", "load_mysql.py"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
